import { shadcn } from '@clerk/themes';

export const clerkAppearance = (basePath: string) => ({
  theme: shadcn,
  cssLayerName: "clerk",
  options: {
    logoPlacement: "inside" as const,
    logoLinkUrl: basePath || "/",
    logoImageUrl: `${window.location.origin}${basePath}/logo.svg`,
  },
  variables: {
    colorPrimary: "hsl(220 50% 15%)",
    colorForeground: "hsl(220 50% 10%)",
    colorMutedForeground: "hsl(215 20% 45%)",
    colorDanger: "hsl(0 70% 50%)",
    colorBackground: "hsl(0 0% 100%)",
    colorInput: "hsl(210 15% 90%)",
    colorInputForeground: "hsl(220 50% 10%)",
    colorNeutral: "hsl(210 15% 90%)",
    fontFamily: "'Outfit', sans-serif",
    borderRadius: "0.25rem",
  },
  elements: {
    rootBox: "w-full flex justify-center",
    cardBox: "bg-white rounded-md w-[440px] max-w-full overflow-hidden shadow-xl border border-border",
    card: "!shadow-none !border-0 !bg-transparent !rounded-none",
    footer: "!shadow-none !border-0 !bg-transparent !rounded-none",
    headerTitle: "text-2xl font-bold text-primary",
    headerSubtitle: "text-muted-foreground",
    socialButtonsBlockButtonText: "font-semibold text-foreground",
    formFieldLabel: "text-sm font-medium text-foreground",
    footerActionLink: "text-accent font-medium hover:underline",
    footerActionText: "text-muted-foreground",
    dividerText: "text-muted-foreground",
    identityPreviewEditButton: "text-accent",
    formFieldSuccessText: "text-green-600",
    alertText: "text-destructive",
    logoBox: "h-12 w-12 mx-auto",
    logoImage: "object-contain",
    socialButtonsBlockButton: "border-border hover:bg-muted transition-colors",
    formButtonPrimary: "bg-primary hover:bg-primary/90 text-primary-foreground font-semibold rounded-md",
    formFieldInput: "bg-background border-input text-foreground rounded-md focus:ring-2 focus:ring-ring",
    footerAction: "bg-muted py-4 px-6 rounded-b-md border-t border-border",
    dividerLine: "bg-border",
    alert: "bg-destructive/10 border-destructive text-destructive",
    otpCodeFieldInput: "bg-background border-input text-foreground",
    formFieldRow: "mb-4",
    main: "px-8 py-6",
  },
});
